// presale-widget/components/Widget/tabs/BuyTab.tsx
import React, { useEffect, useState } from "react";
import StageBox from "../components/StageBox";
import TokenSelectGrid from "../components/TokenSelectGrid";
import { api, API } from "../../../presale-gg/api";
import {
  BuyState,
  buyWithCard,
  buyWithCrypto,
  formatDollar,
  formatLargeNumber,
  formatPrecision,
  parseNum,
} from "../../../presale-gg/util";
import {
  refetchUserData,
  refetchUserStakeData,
  showConnectWalletModal,
  useApiState,
  useUserState,
} from "../../../presale-gg/stores";
import TokenAmountInputs from "../components/TokenAmountInputs";
import { Button } from "../../ui/button";
import { useAccount } from "wagmi";
import CodeInputs, {
  BonusCodeInput,
  ReferralCodeInput,
} from "../components/CodeInputs";
import clsx from "clsx";
import UserReferralLink from "../components/UserReferralData";
import Image from "next/image";
import { toast } from "sonner";
import Spinner from "../components/Spinner";
import WalletTransferModal from "../components/WalletTransferModal";
import NowpaymentsModal from "../components/NowPaymentsModal";
import ContactModal from "../components/ContactModal";
import Modal from "../components/Modal";
import { Loadable } from "../components/Loader";
import { useTranslations } from "next-intl";
import { LAUNCH_PRICE } from "../../constants/numbers";

const BuyTab = () => {
  const t = useTranslations("widget.buy");
  const [selectedToken, setSelectedToken] = useState<API.PaymentToken | null>(
    null
  );
  const [paymentAmountStr, setPaymentAmountStr] = useState("1");
  const [receiveAmountStr, setReceiveAmountStr] = useState("0");

  const apiData = useApiState();

  useEffect(() => {
    if (!apiData.paymentTokens?.length) return;
    setSelectedToken(
      apiData.paymentTokens.find(
        (token) => token.symbol.toUpperCase() === "ETH"
      ) ?? apiData.paymentTokens[0]
    );
  }, [apiData.paymentTokens]);

  useEffect(() => {
    if (!selectedToken) return;
    const receiveNum =
      (parseNum(paymentAmountStr) * parseNum(selectedToken.price)) /
      parseNum(apiData.stage?.token_price ?? 1);
    setReceiveAmountStr(formatPrecision(receiveNum, 0, 2));
  }, [selectedToken, apiData.stage?.token_price]);

  const accountData = useAccount();

  const [visibleOption, setVisibleOption] = useState<
    "bonus" | "referral" | "referral-link" | null
  >(null);

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    if (params.has("referral_code")) setVisibleOption("referral");
    if (params.has("bonus_code")) setVisibleOption("bonus");
  }, []);

  const [transactionLoading, setTransactionLoading] = useState(false);
  const [createdTransaction, setCreatedTransaction] =
    useState<API.Transaction | null>(null);
  const [transactionModalOpen, setTransactionModalOpen] = useState(false);

  const [buyState, setBuyState] = useState<BuyState["type"] | null>(null);
  const [boughtTransaction, setBoughtTransaction] =
    useState<API.PurchaseTransactionHistoryItemV2 | null>(null);
  const [boughtTransactionHash, setBoughtTransactionHash] = useState<
    string | null
  >(null);
  const [boughtPaymentToken, setBoughtPaymentToken] =
    useState<API.PaymentToken | null>(null);
  const [boughtPaymentAmountStr, setBoughtPaymentAmountStr] = useState<
    string | null
  >(null);
  const [boughtModalOpen, setBoughtModalOpen] = useState(false);
  const [contactModalOpen, setContactModalOpen] = useState(false);
  const [transactionErrorMessage, setTransactionErrorMessage] = useState<
    string | null
  >(null);

  const buy = async () => {
    const account = accountData.address;
    if (apiData.presaleEnded) return toast.error(t("presaleEnded"));
    if (!account) return toast.error(t("youMustConnect"));
    if (transactionLoading) return;
    if (!selectedToken) return;
    setTransactionLoading(true);
    try {
      if (selectedToken.symbol.toLowerCase() === "card") {
        await buyCard();
      } else {
        setBuyState(null);
        setBoughtModalOpen(true);
        setBoughtTransaction(null);
        setBoughtTransactionHash(null);
        setBoughtPaymentToken(selectedToken);
        setBoughtPaymentAmountStr(paymentAmountStr);
        setTransactionLoading(true);
        const res = await buyWithCrypto({
          paymentToken: selectedToken,
          paymentTokenNum: paymentAmountStr,
          walletAddress: account,
          onStateChanged: (state) => {
            setBuyState(state.type);
            if (state.type === "confirming") {
              setBoughtTransactionHash(state.transactionHash);
            } else if (state.type === "finished") {
              setBoughtTransaction(state.transaction);
              refetchUserData();
              refetchUserStakeData();
            } else if (state.type === "errored") {
              setTransactionErrorMessage(
                api.getApiErrorMessage(state.error, "Error sending transaction")
              );
            }
            if (state.type !== "sending") {
              setTransactionLoading(false);
            }
          },
        });
        if (!res) return setTransactionLoading(false);
        if (res.type === "created") {
          setCreatedTransaction(res.transaction);
          setTimeout(() => {
            setTransactionModalOpen(true);
          }, 50);
          setTransactionLoading(false);
        }
      }
    } catch (err) {
      console.error(err);
      setTransactionLoading(false);
    }
  };

  const [successModalOpen, setSuccessModalOpen] = useState(false);
  const [erroredModalOpen, setErroredModalOpen] = useState(false);
  const [pendingModalOpen, setPendingModalOpen] = useState(false);
  const [successBoughtModalOpen, setSuccessBoughtModalOpen] = useState(false);

  const buyCard = async () => {
    try {
      const account = accountData.address;
      if (!account) return toast.error(t("youMustConnect"));
      const usdAmount = parseNum(paymentAmountStr);
      await buyWithCard({
        name: `${formatLargeNumber(parseNum(receiveAmountStr))} $DOGEBALL`,
        usd: usdAmount,
        walletAddress: account,
        onClosedEarly: () => {
          setPendingModalOpen(true);
        },
        onError: () => setErroredModalOpen(true),
        onSuccess: (tokens) => {
          if (tokens !== undefined) {
            setSuccessBoughtModalOpen(true);
          } else {
            setSuccessModalOpen(true);
          }
          refetchUserData();
          refetchUserStakeData();
        },
      });
    } catch (err) {}
    setTransactionLoading(false);
  };

  const userData = useUserState();

  return (
    <>
      <Loadable
        component="p"
        className="text-lg text-center self-center font-bold"
        length={6}
      >
        {apiData.presaleEnded ? t("presaleEnded") : apiData.stage?.stage_name}
      </Loadable>
      {!apiData.presaleEnded && (
        <>
          <StageBox />
          <Loadable
            component="p"
            className="text-center text-sm leading-[1] self-center"
            length={12}
          >
            1 $DOGEBALL ={" "}
            {formatDollar(parseNum(apiData.stage?.token_price), true, 0, 6)}
          </Loadable>
        </>
      )}
      {userData.user && (
        <div className="flex gap-2 bg-[rgba(255,255,255,0.15)] rounded-md">
          {[
            {
              label: t("yourTokens"),
              value: `${formatLargeNumber(
                parseNum(userData.user.total_tokens)
              )}`,
            },
            {
              label: t("valueUsd"),
              value: `$${formatLargeNumber(
                parseNum(userData.user.total_tokens) * LAUNCH_PRICE
              )}`,
            },
          ].map((item, i) => (
            <React.Fragment key={i}>
              {i > 0 && (
                <div className="w-[1px] h-8 my-auto bg-[rgba(255,255,255,0.1)]" />
              )}
              <div
                className={clsx(
                  "flex flex-1 flex-col gap-[0.125rem] text-center leading-[1] p-[0.375rem]"
                )}
              >
                <p>{item.value}</p>
                <Loadable
                  component="p"
                  className="text-xs text-[var(--text-secondary)]"
                >
                  {item.label}
                </Loadable>
              </div>
            </React.Fragment>
          ))}
        </div>
      )}
      <TokenSelectGrid value={selectedToken} onChange={setSelectedToken} />
      <TokenAmountInputs
        paymentAmountStr={paymentAmountStr}
        receiveAmountStr={receiveAmountStr}
        onPaymentAmountChange={setPaymentAmountStr}
        onReceiveAmountStr={setReceiveAmountStr}
        selectedToken={selectedToken}
      />
      <Button
        onClick={() => {
          if (!accountData.isConnected) {
            showConnectWalletModal();
          } else {
            buy();
          }
        }}
      >
        {apiData.presaleEnded ? (
          t("presaleEnded")
        ) : transactionLoading ? (
          <Spinner size={5} />
        ) : accountData.isConnected ? (
          t("buyDogeball")
        ) : (
          t("connectWallet")
        )}
      </Button>
      <div className="p-2 border border-[rgba(255,255,255,0.3)] leading-[1.2] text-sm rounded-md text-center">
        {t("bonusOffer")}{" "}
        <span className="font-bold text-[#007BF9]">DOGEBALL10</span>{" "}
        {t("toGetMore")}
      </div>
      <div className="flex justify-center items-center gap-2">
        {(
          [
            { label: t("bonusCode"), value: "bonus" },
            { label: t("referralCode"), value: "referral" },
          ] as const
        ).map((item) => (
          <button
            key={item.value}
            onClick={() =>
              setVisibleOption((option) =>
                option === item.value ? null : item.value
              )
            }
            className={clsx(
              "text-xs py-[0.125rem] px-2 rounded-full cursor-pointer transition-colors",
              {
                "bg-[#007BF9]": visibleOption === item.value,
                "bg-[rgba(255,255,255,0.15)]": visibleOption !== item.value,
              }
            )}
          >
            {item.label}
          </button>
        ))}
      </div>
      {visibleOption === "bonus" && <BonusCodeInput />}
      {visibleOption === "referral" && <ReferralCodeInput />}

      <a
        href="https://presale.gg"
        target="_blank"
        className="flex items-center text-center justify-center gap-1 text-xs hover:underline"
      >
        {t("poweredBy")}{" "}
        <Image
          src="/presale-gg-logo.svg"
          alt="presale.gg"
          width="109"
          height="109"
          className="h-4 w-auto"
        />
        Presale.gg
      </a>

      {createdTransaction && (
        <NowpaymentsModal
          open={transactionModalOpen}
          onClose={() => {
            setTransactionModalOpen(false);
            setContactModalOpen(true);
          }}
          transaction={createdTransaction}
        />
      )}
      {boughtPaymentAmountStr !== null &&
        boughtPaymentToken !== null &&
        buyState !== null && (
          <WalletTransferModal
            open={boughtModalOpen}
            onClose={() => {
              setBoughtModalOpen(false);
              setContactModalOpen(true);
            }}
            payCurrency={boughtPaymentToken}
            payAmount={boughtPaymentAmountStr}
            state={buyState}
            transactionHash={boughtTransactionHash}
            transaction={boughtTransaction}
            transactionError={transactionErrorMessage}
          />
        )}
      <ContactModal
        open={contactModalOpen}
        onClose={() => setContactModalOpen(false)}
      />
      <Modal
        title={t("transactionSuccessful")}
        open={successModalOpen}
        onClose={() => {
          setSuccessModalOpen(false);
          setContactModalOpen(true);
        }}
      >
        <p>{t("transactionSuccessfulDesc")}</p>
      </Modal>
      <Modal
        title={t("transactionSuccessful")}
        open={successBoughtModalOpen}
        onClose={() => {
          setSuccessBoughtModalOpen(false);
          setContactModalOpen(true);
        }}
      >
        <p>
          {t("transactionSuccessfulDesc")} {t("youBought")}{" "}
          {boughtTransaction?.tokens_bought ?? "Unknown"} DOGEBALL.
        </p>
      </Modal>
      <Modal
        title={t("transactionErrored")}
        open={erroredModalOpen}
        onClose={() => setErroredModalOpen(false)}
      >
        <p>{t("transactionErroredDesc")}</p>
      </Modal>
      <Modal
        title={t("transactionPending")}
        open={pendingModalOpen}
        onClose={() => {
          setPendingModalOpen(false);
          setContactModalOpen(true);
        }}
      >
        <p>{t("transactionPendingDesc")}</p>
      </Modal>
    </>
  );
};

export default BuyTab;

// src/components/PresaleWidget/tabs/BuyTab.vue
<template>
  <div class="flex flex-col gap-4 w-full min-w-0 max-w-full">
    <!-- Stage Box (only if presale active) -->
    <template v-if="!presale.presaleEnded.value">
      <StageBox />
      <p
        class="text-center self-center text-white font-grotesk text-sm font-semibold leading-none"
      >
        1 $DOGEBALL =
        {{
          formatDollar(parseNum(presale.stage.value?.token_price), true, 0, 6)
        }}
      </p>
    </template>

    <!-- Payment Methods -->
    <TokenSelectGrid :value="selectedToken" @update:value="setSelectedToken" />

    <!-- Presale/Launch Price Bar -->
    <div
      class="flex px-3 sm:px-4 py-2 max-md:justify-center justify-between sm:justify-center items-center gap-1 self-stretch rounded-2xl border border-white/20 bg-[rgba(8,12,35,0.48)]"
    >
      <span
        class="gap-1 max-md:gap-0.5 text-white text-sm max-md:text-xs font-semibold leading-5 font-grotesk whitespace-nowrap overflow-hidden text-ellipsis h-full flex items-center font-feature-off"
      >
        {{ t("presale.buyTab.presalePrice") }}
        <span class="text-[#59A6FD]">
          {{
            formatDollar(parseNum(presale.stage.value?.token_price), true, 0, 4)
          }}
        </span>
        <span> | </span>
        <span>{{ t("presale.buyTab.launchPrice") }}</span>
        <span class="text-[#59A6FD]">
          {{ formatDollar(LAUNCH_PRICE, true, 0, 4) }}
        </span>
      </span>
    </div>

    <!-- Token Amount Inputs -->
    <TokenAmountInputs
      :selected-token="selectedToken"
      v-model:payment-amount="paymentAmountStr"
      v-model:receive-amount="receiveAmountStr"
    />

    <!-- Main Action Button -->
    <Button
      :disabled="isBuying || presale.presaleEnded.value"
      variant="primary"
      class="w-full h-11 px-6 !bg-[#EB4102] !bg-none text-base font-semibold"
      style="border-radius: 80px"
    >
      <Spinner v-if="isBuying" :size="5" />
      <template v-else>
        <span v-if="presale.presaleEnded.value">{{
          t("presale.buyTab.presaleEnded")
        }}</span>
        <span v-else-if="!presale.isConnected.value">{{
          t("presale.buyTab.connectWallet")
        }}</span>
        <span v-else>{{ buyButtonText }}</span>
      </template>
    </Button>

    <!-- Buy State Message -->
    <p
      v-if="buyStateMessage"
      class="text-center text-sm text-white/70 font-grotesk"
    >
      {{ buyStateMessage }}
    </p>

    <div class="relative h-10">
      <!-- Code Input Buttons -->
      <Transition name="slide-fade" mode="out-in">
        <div v-if="!visibleOption" class="flex flex-row justify-center items-center gap-3 absolute left-0 right-0 top-1/2 -translate-y-1/2">
          <PillButton
            v-for="item in codeOptions"
            :key="item.value"
            :active="visibleOption === item.value"
            @click="toggleCodeOption(item.value)"
          >
            {{ item.label }}
          </PillButton>
        </div>
      </Transition>

      <!-- Code Inputs -->
      <Transition name="slide-fade" mode="out-in">
        <div v-if="visibleOption" class="flex gap-2 absolute left-0 right-0 top-1/2 -translate-y-1/2">
          <BonusCodeInput v-if="visibleOption === 'bonus'" class="flex-1" />
          <ReferralCodeInput v-else-if="visibleOption === 'referral'" class="flex-1" />
          <button
            @click="visibleOption = null"
            class="h-8 w-8 flex items-center justify-center my-auto ml-auto rounded-full hover:bg-[rgba(255,255,255,0.1)] cursor-pointer transition-colors"
          >
            <CloseIcon class="h-5 w-5" />
          </button>
        </div>
      </Transition>
    </div>

    <NowPaymentsModal
      v-if="nowPaymentsTransaction"
      :open="nowPaymentsModalVisible"
      @close="() => (nowPaymentsModalVisible = false)"
      :transaction="nowPaymentsTransaction"
    />
    <WalletTransferModal
      v-if="presale.currentPurchase.value"
      :open="walletTransferModalVisible"
      @close="closeWalletTransfer"
      :pay-amount="presale.currentPurchase.value.payAmount"
      :pay-currency="presale.currentPurchase.value.token"
      :state="presale.currentPurchase.value.state"
      :transaction="presale.currentPurchase.value.transaction"
      :transaction-hash="presale.currentPurchase.value.transactionHash"
      :transaction-error="presale.currentPurchase.value.error"
    />
    <ContactModal
      :open="contactModalVisible"
      @close="() => (contactModalVisible = false)"
    />
  </div>
</template>

<script setup>
import { useI18n } from "vue-i18n";
import { ref, watch, computed, onMounted, watchEffect } from "vue";
import StageBox from "../stage/StageBox.vue";
import { TokenSelectGrid, TokenAmountInputs } from "../token";
import { Button, Spinner, PillButton } from "../ui";
import BonusCodeInput from "../code/BonusCodeInput.vue";
import ReferralCodeInput from "../code/ReferralCodeInput.vue";
import { usePresale, BuyStateType } from "@/composables/usePresale";
import { useToast } from "@/composables/useToast";
import { formatDollar, parseNum, formatPrecision } from "@/utils/format";
import { LAUNCH_PRICE, DEFAULT_PAYMENT_AMOUNT } from "@/config/presale";
import { presaleApi } from "@/api";
import NowPaymentsModal from "../modals/NowPaymentsModal.vue";
import WalletTransferModal from "../modals/WalletTransferModal.vue";
import { isWalletTransferSupported } from "@/utils/web3";
import ContactModal from "../modals/ContactModal.vue";
import CloseIcon from "@/assets/icons/Close.vue"

const { t } = useI18n();

const presale = usePresale();
const toast = useToast();

watchEffect(() => console.log(presale.isConnected.value));

// Local state
const selectedToken = ref(null);
const paymentAmountStr = ref(DEFAULT_PAYMENT_AMOUNT);
const receiveAmountStr = ref("0");
const visibleOption = ref(null);

const codeOptions = computed(() => [
  { label: t("presale.buyTab.bonusCode"), value: "bonus" },
  { label: t("presale.buyTab.referralCode"), value: "referral" },
]);

// Computed
const isBuying = computed(() => {
  const state = presale.buyState.value.type;
  return (
    [
      BuyStateType.SENDING,
      BuyStateType.CONFIRMING,
      BuyStateType.FINALIZING,
    ].includes(state) || presale.buyLoading.value
  );
});

const buyButtonText = computed(() => {
  if (!selectedToken.value) return t("presale.buyTab.selectToken");
  if (parseNum(paymentAmountStr.value) <= 0)
    return t("presale.buyTab.enterAmount");
  if (selectedToken.value.symbol.toUpperCase() === "CARD") {
    return t("presale.buyTab.buyWithCard");
  }
  return t("presale.buyTab.comingSoon");
});

const buyStateMessage = computed(() => {
  const state = presale.buyState.value;
  switch (state.type) {
    case BuyStateType.SENDING:
      return t("presale.buyTab.confirmTransaction");
    case BuyStateType.CONFIRMING:
      return t("presale.buyTab.waitingConfirmation");
    case BuyStateType.FINALIZING:
      return t("presale.buyTab.processingPurchase");
    default:
      return null;
  }
});

// Initialize selected token
watch(
  () => presale.paymentTokens.value,
  (tokens) => {
    if (!tokens?.length) return;
    const ethToken = tokens.find(
      (token) => token.symbol.toUpperCase() === "ETH"
    );
    selectedToken.value = ethToken ?? tokens[0];
  },
  { immediate: true }
);

// Calculate receive amount when payment changes
watch(
  [selectedToken, () => presale.stage.value?.token_price],
  () => {
    if (!selectedToken.value || !presale.stage.value) return;
    const receiveNum = presale.calculateReceiveAmount(
      paymentAmountStr.value,
      selectedToken.value
    );
    receiveAmountStr.value = (
      Math.floor(receiveNum * 10 ** 2) /
      10 ** 2
    ).toString();
  },
  { immediate: true }
);

// Check URL params for code inputs on mount
onMounted(() => {
  const params = new URLSearchParams(window.location.search);
  if (params.has("referral_code")) visibleOption.value = "referral";
  if (params.has("bonus_code")) visibleOption.value = "bonus";
});

// Methods
const setSelectedToken = (token) => {
  selectedToken.value = token;
};

const toggleCodeOption = (value) => {
  visibleOption.value = visibleOption.value === value ? null : value;
};

/** @type {import("vue").Ref<import("@/api/api.types").API.Transaction | null>} */
const nowPaymentsTransaction = ref(null);
const nowPaymentsModalVisible = ref(false);
const walletTransferModalVisible = ref(false);

const contactModalVisible = ref(false);

const closeWalletTransfer = () => {
  walletTransferModalVisible.value = false;
  contactModalVisible.value = true;
};

const handleBuy = async () => {
  // Connect wallet if not connected
  if (!presale.isConnected.value) {
    presale.showConnectWalletModal();
    return;
  }

  // Validation
  if (presale.presaleEnded.value) {
    toast.showError(t("presale.errors.presaleEnded"));
    return;
  }

  if (!selectedToken.value) {
    toast.showError(t("presale.errors.selectPaymentMethod"));
    return;
  }

  const paymentAmount = parseNum(paymentAmountStr.value);
  if (paymentAmount <= 0) {
    toast.showError(t("presale.errors.enterAmount"));
    return;
  }

  // Handle card payment
  if (selectedToken.value.symbol.toUpperCase() === "CARD") {
    try {
      const usdAmount = paymentAmount; // For card, payment is in USD
      await presale.buyWithCard({
        usdAmount,
        onSuccess: (tokensBought) => {
          toast.showSuccess(
            `Successfully purchased ${formatPrecision(
              tokensBought,
              0,
              2
            )} $DOGEBALL!`
          );
        },
        onError: () => {
          toast.showError(t("presale.errors.cardPaymentFailed"));
        },
        onClosedEarly: () => {
          toast.showInfo(t("presale.errors.paymentProcessing"));
        },
      });
    } catch (err) {
      console.error("Card payment error:", err);
    }
    return;
  }

  // Handle crypto payment
  try {
    const result = await presale.buyWithCrypto({
      paymentToken: selectedToken.value,
      paymentAmount: paymentAmountStr.value,
      onStateChanged: (state) => {
        if (
          state.state === "sending" &&
          isWalletTransferSupported(selectedToken.value)
        ) {
          setTimeout(() => (walletTransferModalVisible.value = true), 50);
        }
        if (state.state === BuyStateType.FINISHED) {
          const tokensReceived = parseNum(receiveAmountStr.value);
          toast.showSuccess(
            `Successfully purchased ${formatPrecision(
              tokensReceived,
              0,
              2
            )} $DOGEBALL!`
          );
        }
      },
    });

    // Handle NowPayments flow (shows payment modal)
    if (result?.type === "created" && result.transaction) {
      toast.showInfo("Complete your payment in the popup window");
      nowPaymentsTransaction.value = result.transaction;
      setTimeout(() => (nowPaymentsModalVisible.value = true), 50);
    }
  } catch (err) {
    const message = presaleApi.getApiErrorMessage(
      err,
      t("presale.errors.transactionFailed")
    );
    toast.showError(message);
    console.error("Buy error:", err);
  }
};
</script>

<style scoped>
.slide-fade-enter-active,
.slide-fade-leave-active {
  transition: all 0.2s ease;
}

.slide-fade-enter-from,
.slide-fade-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}
</style>
