// src/components/PresaleWidget/transaction/TransactionHistoryList.vue
<template>
  <div class="flex flex-col gap-2 flex-1 overflow-y-auto min-h-0">
    <!-- Loading State -->
    <div v-if="loading" class="flex flex-col gap-2">
      <Skeleton v-for="i in 3" :key="i" class="h-20 w-full rounded-md" />
    </div>

    <!-- Empty State -->
    <div
      v-else-if="formattedTransactions.length === 0"
      class="flex flex-col items-center justify-center gap-3 py-8 text-white/60"
    >
      <svg
        class="w-12 h-12"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="1.5"
          d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"
        />
      </svg>
      <p class="text-sm font-grotesk">
        {{ t("presale.historyTab.noTransactions") }}
      </p>
      <p class="text-xs text-white/40">
        {{ t("presale.historyTab.purchasesWillAppear") }}
      </p>
    </div>

    <!-- Transaction List -->
    <template v-else>
      <div
        v-for="trx in formattedTransactions"
        :key="trx.id"
        class="bg-white/10 p-2.5 sm:p-3 rounded-md flex flex-col gap-2 hover:bg-white/15 transition-colors"
      >
        <!-- Status Chips -->
        <div class="flex gap-1.5 sm:gap-2 flex-wrap">
          <TransactionChip
            v-for="(chip, idx) in getChips(trx)"
            :key="idx"
            :bg="chip.bg"
            :text-color="chip.textColor"
          >
            {{ chip.text }}
          </TransactionChip>
        </div>

        <!-- Transaction Details -->
        <div class="flex flex-col sm:flex-row gap-2 sm:gap-4 sm:items-center">
          <div class="flex-1 min-w-0">
            <!-- Transaction Type Content -->
            <template v-if="trx.record_type === 'transaction'">
              <p class="text-xs sm:text-sm font-medium break-words text-white">
                {{ formatLargeNumber(parseNum(trx.payment_token_amount)) }}
                {{ trx.payment_token_name?.toUpperCase() }}
              </p>
              <p
                v-if="trx.tokens_bought !== null"
                class="text-[10px] sm:text-xs text-white/60 break-words"
              >
                {{ formatLargeNumber(parseNum(trx.tokens_bought)) }} $DOGEBALL
                {{ t("presale.transactionDetails.for")
                }}{{ formatLargeNumber(parseNum(trx.payment_usd_amount)) }}
              </p>
              <p v-else class="text-[10px] sm:text-xs text-white/60">
                {{
                  trx.status === "pending"
                    ? t("presale.transactions.awaitingPayment")
                    : t("presale.transactions.processing")
                }}
              </p>
            </template>

            <template v-else-if="trx.record_type === 'manual_transaction'">
              <p class="text-xs sm:text-sm font-medium break-words text-white">
                +{{ formatLargeNumber(parseNum(trx.tokens_bought)) }} $DOGEBALL
              </p>
            </template>

            <template v-else-if="trx.record_type === 'bonus_transaction'">
              <p class="text-xs sm:text-sm font-medium break-words text-white">
                +{{ formatLargeNumber(parseNum(trx.bonus_token_amount)) }}
                $DOGEBALL
              </p>
            </template>
          </div>

          <!-- Date -->
          <div class="text-[10px] sm:text-xs text-white/60 flex-shrink-0">
            {{ formatDate(trx.created_at) }}
          </div>
        </div>

        <!-- Reason (for manual transactions) -->
        <p
          v-if="trx.record_type === 'manual_transaction' && trx.reason"
          class="text-[10px] sm:text-xs break-words text-white/80"
        >
          <span class="font-semibold">{{
            t("presale.transactionDetails.reason")
          }}</span>
          {{ trx.reason }}
        </p>

        <!-- Extras (bonuses associated with this transaction) -->
        <div
          v-if="trx.extras && trx.extras.length > 0"
          class="flex flex-wrap gap-2 pt-1 border-t border-white/10"
        >
          <div
            v-for="(extra, idx) in trx.extras"
            :key="idx"
            class="text-[10px] text-white/60 bg-white/5 px-2 py-0.5 rounded"
          >
            {{ extra.label }}: +{{
              formatLargeNumber(parseNum(extra.tokens_received))
            }}
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup>
import { ref, computed, watch, onMounted } from "vue";
import { useI18n } from "vue-i18n";
import { Spinner, Skeleton } from "../ui";
import TransactionChip from "./TransactionChip.vue";
import { usePresale } from "@/composables/usePresale";
import { formatLargeNumber, parseNum, capitalize } from "@/utils/format";

const { t } = useI18n();
const presale = usePresale();

const loading = ref(true);
const transactions = ref([]);

const STATUS_COLORS = {
  completed: ["#00bf9a", "#fff"],
  success: ["#00bf9a", "#fff"],
  error: ["#fa332f", "#fff"],
  failed: ["#fa332f", "#fff"],
  expired: ["#fa332f", "#fff"],
  pending: ["#bf7e15", "#fff"],
  waiting: ["#bf7e15", "#fff"],
  finalising: ["#0c6db3", "#fff"],
  processing: ["#0c6db3", "#fff"],
  confirming: ["#0c6db3", "#fff"],
  refunded: ["#00bf9a", "#fff"],
};

const groupedTransactions = computed(() => {
  const groups = [];

  transactions.value.forEach((trx) => {
    const trxId =
      "parent_transaction_id" in trx
        ? parseNum(trx.parent_transaction_id)
        : trx.record_type === "transaction"
        ? parseNum(trx.id)
        : null;

    if (trxId === null) {
      groups.push({ transactionId: null, transactions: [trx] });
      return;
    }

    let group = groups.find((g) => g.transactionId === trxId);
    if (!group) {
      group = { transactionId: trxId, transactions: [] };
      groups.push(group);
    }
    group.transactions.push(trx);
  });

  const getSortOrder = (type) =>
    ({
      transaction: 0,
      manual_transaction: 1,
      bonus_transaction: 2,
    }[type] ?? 3);

  groups.forEach((group) => {
    group.transactions.sort(
      (a, b) => getSortOrder(a.record_type) - getSortOrder(b.record_type)
    );
  });

  return groups;
});

const formattedTransactions = computed(() => {
  return groupedTransactions.value.map((group) => {
    if (group.transactions.length === 1) {
      return { ...group.transactions[0], extras: [] };
    }

    return {
      ...group.transactions[0],
      extras: group.transactions.slice(1).map((trx) => ({
        label:
          trx.record_type === "bonus_transaction"
            ? capitalize(trx.bonus_type)
            : trx.record_type === "manual_transaction"
            ? t("presale.transactions.manual")
            : trx.record_type === "transaction"
            ? t("presale.transactions.purchase")
            : "",
        tokens_received:
          trx.record_type === "bonus_transaction"
            ? trx.bonus_token_amount
            : trx.record_type === "manual_transaction" ||
              trx.record_type === "transaction"
            ? trx.tokens_bought
            : "0",
      })),
    };
  });
});

const getChips = (trx) => {
  const chips = [
    {
      text: capitalize(
        trx.record_type === "bonus_transaction"
          ? trx.bonus_type
          : trx.record_type === "transaction"
          ? t("presale.transactions.purchase").toLowerCase()
          : trx.record_type?.replace("_", " ") || "transaction"
      ),
      bg: "#444",
      textColor: "#fff",
    },
  ];

  if (trx.status) {
    const statusKey = trx.status.toLowerCase();
    chips.push({
      text: capitalize(statusKey === "pending" ? "unpaid" : statusKey),
      bg: STATUS_COLORS[statusKey]?.[0] || "#444",
      textColor: STATUS_COLORS[statusKey]?.[1] || "#fff",
    });
  }

  if ("stage_name" in trx && trx.stage_name) {
    chips.push({
      text: trx.stage_name,
      bg: "#333",
      textColor: "#fff",
    });
  }

  return chips;
};

const formatDate = (dateStr) => {
  const date = new Date(dateStr);
  return date.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
};

const fetchTransactions = async () => {
  if (!presale.address.value) {
    transactions.value = [];
    loading.value = false;
    return;
  }

  loading.value = true;
  try {
    const data = await presale.getTransactionHistory(0, 50);
    transactions.value = data || [];
  } catch (err) {
    console.error("Failed to fetch transactions:", err);
    transactions.value = [];
  }
  loading.value = false;
};

// Fetch transactions when address changes
watch(
  () => presale.address.value,
  () => fetchTransactions(),
  { immediate: true }
);

// Refetch when buy state changes to finished
watch(
  () => presale.buyState.value,
  (state) => {
    if (state.type === "finished") {
      // Delay refetch to allow backend to process
      setTimeout(fetchTransactions, 2000);
    }
  }
);
</script>

// presale-widget/components/Widget/components/TransactionHistoryList/TransactionHistoryList.tsx
import { capitalize, formatLargeNumber, parseNum } from "../../../presale-gg/util";
import classes from "./TransactionHistoryItemList.module.css";
import { api, API } from "../../../presale-gg/api";
import { useEffect, useMemo, useState } from "react";
import { useAccount } from "wagmi";
import Spinner from "../Spinner";
import { tokenNameMap } from "../../../presale-gg/assets/img/tokens";
import Image from "next/image";

const TransactionHistoryList = () => {
  const [loading, setLoading] = useState(true);
  const [transactions, setTransactions] = useState<
    API.TransactionHistoryItemV2[]
  >([]);
  const accountData = useAccount();

  const groupedTransactions = useMemo(() => {
    const groups: {
      transactionId: number | null;
      transactions: API.TransactionHistoryItemV2[];
    }[] = [];
    transactions.forEach((trx) => {
      const trxId =
        "parent_transaction_id" in trx
          ? parseNum(trx.parent_transaction_id)
          : trx.record_type === "transaction"
          ? parseNum(trx.id)
          : null;
      if (trxId === null) {
        groups.push({ transactionId: null, transactions: [trx] });
        return;
      }
      let group = groups.find((group) => group.transactionId === trxId);
      if (!group) {
        group = { transactionId: trxId, transactions: [] };
        groups.push(group);
      }
      group.transactions.push(trx);
    });
    const getSortOrder = (a: API.TransactionHistoryItemV2["record_type"]) =>
      ({
        transaction: 0,
        manual_transaction: 1,
        bonus_transaction: 2,
      }[a]);
    groups.forEach((group) => {
      group.transactions.sort(
        (a, b) => getSortOrder(a.record_type) - getSortOrder(b.record_type)
      );
    });
    return groups;
  }, [transactions]);

  const formattedTransactions = useMemo(() => {
    return groupedTransactions.map((group) => {
      if (group.transactions.length === 1)
        return { ...group.transactions[0], extras: [] };
      return {
        ...group.transactions[0],
        extras: group.transactions.slice(1).map((trx) => {
          return {
            label:
              trx.record_type === "bonus_transaction"
                ? capitalize(trx.bonus_type)
                : trx.record_type === "manual_transaction"
                ? "Manual"
                : trx.record_type === "transaction"
                ? "Purchase"
                : "",
            tokens_received:
              trx.record_type === "bonus_transaction"
                ? trx.bonus_token_amount
                : trx.record_type === "manual_transaction" ||
                  trx.record_type === "transaction"
                ? trx.tokens_bought
                : "0",
          };
        }),
      };
    });
  }, [groupedTransactions]);

  useEffect(() => {
    const address = accountData.address;
    if (!address) {
      setLoading(false);
      setTransactions([]);
      return;
    }
    setLoading(true);
    let aborted = false;
    api.getTransactionHistoryV2(address, 0, 100).then((res) => {
      if (aborted) return;
      setTransactions(res.data);
      setLoading(false);
    });
    return () => {
      aborted = true;
    };
  }, [accountData.address]);

  const statusColMap = {
    completed: ["#00bf9a", "#0b4b29"],
    error: ["#fa332f", "#000"],
    failed: ["#fa332f", "#000"],
    expired: ["#fa332f", "#000"],
    pending: ["#bf7e15", "#000"],
    finalising: ["#0c6db3", "#000"],
    processing: ["#0c6db3", "#000"],
    refunded: ["#00bf9a", "#000"],
  };

  return (
    <div className={classes["container"]}>
      {loading ? (
        <Spinner size={10} className={classes["spinner"]} />
      ) : (
        <>
          {formattedTransactions.length === 0 && (
            <p className="text-center">You have no transactions</p>
          )}
          {formattedTransactions.map((trx) => (
            <div key={trx.id} className={classes["transaction"]}>
              <div className={classes["tags"]}>
                {[
                  {
                    text: capitalize(
                      trx.record_type === "bonus_transaction"
                        ? trx.bonus_type
                        : trx.record_type === "transaction"
                        ? "purchase"
                        : trx.record_type
                    ),
                    bg: "#333",
                    textColor: "#fff",
                  },
                  trx.status
                    ? {
                        text: capitalize(
                          trx.status === "pending" ? "unpaid" : trx.status
                        ),
                        bg: statusColMap[trx.status][0],
                        textColor: statusColMap[trx.status][1],
                      }
                    : undefined,
                  "stage_name" in trx && trx.stage_name
                    ? { text: trx.stage_name, bg: "#333", textColor: "#fff" }
                    : undefined,
                ]
                  .filter((chip) => chip !== undefined)
                  .map((chip, idx) => (
                    <div
                      key={idx}
                      className={classes["tag"]}
                      style={{
                        backgroundColor: chip.bg,
                        color: chip.textColor,
                      }}
                    >
                      {chip.text}
                    </div>
                  ))}
              </div>
              <div className={classes["info-container"]}>
                <div className={classes["left-info"]}>
                  {trx.record_type === "transaction" &&
                    tokenNameMap[
                      trx.payment_token_name?.toLowerCase() ?? ""
                    ] && (
                      <Image
                        className={classes["token-img"]}
                        src={
                          trx.record_type === "transaction"
                            ? tokenNameMap[
                                trx.payment_token_name?.toLowerCase() ?? ""
                              ]!
                            : "/logo.png"
                        }
                        width={100}
                        height={100}
                        alt=""
                      />
                    )}
                  <div className={classes["info-text-container"]}>
                    {trx.record_type === "transaction" && (
                      <>
                        <p className={classes["info-text"]}>
                          {formatLargeNumber(
                            parseNum(trx.payment_token_amount)
                          )}{" "}
                          {trx.payment_token_name?.toUpperCase()}
                        </p>
                        {trx.tokens_bought !== null ? (
                          <p className={classes["info-text-sm"]}>
                            {formatLargeNumber(parseNum(trx.tokens_bought))}{" "}
                            $DOGEBALL for $
                            {formatLargeNumber(
                              parseNum(trx.payment_usd_amount)
                            )}
                          </p>
                        ) : (
                          <p className={classes["info-text-sm"]}>
                            {trx.status === "pending"
                              ? "Unpaid"
                              : "In progress"}
                          </p>
                        )}
                      </>
                    )}
                    {trx.record_type === "manual_transaction" && (
                      <p className={classes["info-text"]}>
                        +{formatLargeNumber(parseNum(trx.tokens_bought))}{" "}
                        $DOGEBALL
                      </p>
                    )}
                    {trx.record_type === "bonus_transaction" && (
                      <p className={classes["info-text"]}>
                        +{formatLargeNumber(parseNum(trx.bonus_token_amount))}{" "}
                        $DOGEBALL
                      </p>
                    )}
                    {trx.extras.length > 0 && (
                      <div className={classes["extras"]}>
                        {trx.extras.map((extra, idx) => {
                          return (
                            <div key={idx} className={classes["extra"]}>
                              <svg
                                xmlns="http://www.w3.org/2000/svg"
                                width="24"
                                height="24"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="#228f3d"
                                stroke-width="2"
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                className="lucide lucide-circle-plus size-4 text-green-500"
                              >
                                <circle cx="12" cy="12" r="10"></circle>
                                <path d="M8 12h8"></path>
                                <path d="M12 8v8"></path>
                              </svg>
                              {extra.label}:{" "}
                              {`+${formatLargeNumber(
                                parseNum(extra.tokens_received)
                              )} $DOGEBALL`}
                            </div>
                          );
                        })}
                      </div>
                    )}
                  </div>
                </div>
                <div className={classes["right-text"]}>
                  <p className={classes["info-text-sm"]}>
                    {new Date(trx.created_at).toLocaleDateString()}
                  </p>
                </div>
              </div>
              {trx.record_type === "manual_transaction" && (
                <p className={classes["info-text-sm"]}>
                  <span className="bold">Reason:</span> {trx.reason}
                </p>
              )}
            </div>
          ))}
        </>
      )}
    </div>
  );
};

export default TransactionHistoryList;
