// presale-widget/components/Widget/components/TokenSelectGrid.tsx
import { API } from "../../../presale-gg/api";
import TokenSelect from "./TokenSelect";
import React, { useEffect, useMemo, useState } from "react";
import { useApiState } from "../../../presale-gg/stores";
import { groupTokens } from "../../../presale-gg/util";
import clsx from "clsx";
import Image from "next/image";

export type TokenSelectGridProps = Omit<
  React.HTMLAttributes<HTMLDivElement>,
  "onChange"
> & {
  value: API.PaymentToken | null;
  onChange: (newVal: API.PaymentToken | null) => void;
};

const TokenSelectGrid: React.FC<TokenSelectGridProps> = ({
  value,
  onChange,
  ...others
}) => {
  const apiData = useApiState();
  const groupedTokens = useMemo(
    () => groupTokens(apiData.paymentTokens ?? []),
    [apiData.paymentTokens]
  );
  const [selectedGroupIndex, setSelectedGroupIndex] = useState(0);

  useEffect(() => {
    if (!value) return;
    if (groupedTokens[selectedGroupIndex].currencies.includes(value)) return;
    const groupIndex = groupedTokens.findIndex((group) =>
      group.currencies.includes(value)
    );
    if (groupIndex === -1) return;
    setSelectedGroupIndex(groupIndex);
  }, [value, groupedTokens, selectedGroupIndex]);

  return (
    <div {...others} className={clsx("flex flex-col gap-2", others.className)}>
      <div className="grid grid-cols-3 gap-2">
        {groupedTokens.map((list, i) => {
          const selected =
            list.currencies.find((token) => token.id === value?.id) !==
              undefined && i === selectedGroupIndex;

          return (
            <TokenSelect
              key={i}
              value={selected ? value : null}
              onChange={(token) => {
                onChange(token);
                setSelectedGroupIndex(i);
              }}
              defaultLabel={list.defaultLabel}
              placeholder={list.placeholder}
              tokens={list.currencies}
              defaultToken={list.defaultToken}
              selected={selected}
              style={i === 0 ? { gridColumn: "1 / -1" } : {}}
            />
          );
        })}
      </div>
      <div className="flex gap-1 items-center justify-center text-sm">
        <Image
          src="/images/coin-logos.webp"
          width="515"
          height="77"
          alt="ADA, LTC, TRX, TON, XRP, USDC"
          className="h-5 w-auto"
        />
        <span>+ Other Cryptos</span>
      </div>
    </div>
  );
};

export default TokenSelectGrid;

// src/components/PresaleWidget/token/TokenSelectGrid.vue
<template>
  <div class="flex flex-col gap-3">
    <!-- Card Payment Button (Full Width) -->
    <TokenSelect
      v-if="cardToken"
      :value="cardToken.id === value?.id ? value : null"
      :tokens="[cardToken]"
      :default-label="cardToken.symbol"
      :default-token="cardToken"
      :selected="cardToken.id === value?.id"
      class="w-full"
      @update:value="handleTokenChange"
    />

    <!-- Crypto Grid -->
    <div class="grid grid-cols-3 gap-2">
      <TokenSelect
        v-for="tokenGroup in mainCryptoGroups"
        :key="tokenGroup.symbol"
        :value="tokenGroup.tokens.find((t) => t.id === value?.id) || null"
        :tokens="tokenGroup.tokens"
        :default-label="tokenGroup.symbol"
        :default-token="tokenGroup.defaultToken"
        :selected="tokenGroup.tokens.some((t) => t.id === value?.id)"
        @update:value="handleTokenChange"
      />
      <!-- More Button -->
      <TokenSelect
        v-if="moreTokens.length > 0"
        :value="moreTokens.find((t) => t.id === value?.id) || null"
        :tokens="moreTokens"
        :default-label="'More'"
        :placeholder="'More'"
        :selected="moreTokens.some((t) => t.id === value?.id)"
        @update:value="handleTokenChange"
      />
    </div>

    <!-- Other Cryptos Section -->
    <div class="flex flex-col items-center gap-2">
      <div class="flex items-center justify-center gap-2">
        <img
          :src="coinLogosImage"
          alt="Other Cryptos"
          class="h-8 w-auto max-w-[160px] object-contain"
        />
        <span class="text-white font-grotesk text-lg font-medium leading-5 font-feature-off">
          + Other Cryptos
        </span>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from "vue";
import TokenSelect from "./TokenSelect.vue";
import { useApiState } from "@/composables/useApiState";
import coinLogosImage from "@/assets/img/logos/coin-logos.webp";

const props = defineProps({
  value: {
    type: Object,
    default: null,
  },
});

const emit = defineEmits(["update:value"]);

const apiData = useApiState();

const MAIN_CRYPTO_SYMBOLS = ["ETH", "BNB", "USDT", "BTC", "SOL"];

const cardToken = computed(() => {
  const tokens = apiData.paymentTokens.value ?? [];
  return tokens.find((t) => t.symbol.toUpperCase() === "CARD");
});

const tokenGroups = computed(() => {
  const tokens = apiData.paymentTokens.value ?? [];
  const cryptoTokens = tokens.filter((t) => t.symbol.toUpperCase() !== "CARD");

  const groups = {};
  cryptoTokens.forEach((token) => {
    const symbol = token.symbol.toUpperCase();
    if (!groups[symbol]) {
      groups[symbol] = [];
    }
    groups[symbol].push(token);
  });

  return groups;
});

const mainCryptoGroups = computed(() => {
  return MAIN_CRYPTO_SYMBOLS.filter((symbol) => tokenGroups.value[symbol]).map(
    (symbol) => ({
      symbol,
      tokens: tokenGroups.value[symbol],
      defaultToken: tokenGroups.value[symbol][0],
    })
  );
});

const moreTokens = computed(() => {
  const tokens = apiData.paymentTokens.value ?? [];
  return tokens.filter(
    (t) =>
      t.symbol.toUpperCase() !== "CARD" &&
      !MAIN_CRYPTO_SYMBOLS.includes(t.symbol.toUpperCase())
  );
});

const handleTokenChange = (token) => {
  emit("update:value", token);
};
</script>
