// src/components/PresaleWidget/Widget.vue
<template>
  <Loader :loading="isLoading">
    <div
      class="flex flex-col w-full rounded-3xl text-white overflow-hidden font-normal relative p-6 items-center gap-2.5 border border-white/20 bg-[rgba(23,138,184,0.40)] shadow-[0_0_14px_0_#5464D8] backdrop-blur-[5px] transition-[height] duration-200 ease-out"
      :style="{ height: '55rem' }"
    >
      <div
        ref="innerRef"
        class="flex flex-col gap-4 flex-shrink-0 w-full justify-start flex-1 h-0"
      >
        <!-- Tab Wrapper -->
        <div class="flex items-center justify-center w-full">
          <div
            class="inline-flex items-center gap-1 rounded-[80px] flex-wrap justify-center"
            style="background: rgba(255, 255, 255, 0.15)"
          >
            <button
              v-for="tab in tabs"
              :key="tab.key"
              :class="[
                'flex items-center justify-center gap-1 sm:gap-1.5 px-3 sm:px-4 py-2 rounded-full font-medium relative overflow-hidden text-sm sm:text-base font-grotesk transition-all duration-300',
                selectedTabKey === tab.key
                  ? 'bg-white text-[#212F5C] shadow-md'
                  : 'text-white hover:bg-white/10',
              ]"
              @click="setSelectedTabKey(tab.key)"
            >
              <component
                :is="tab.icon"
                :color="selectedTabKey === tab.key ? '#212F5C' : '#FFF'"
                class="w-4 h-4 flex-shrink-0 transition-colors duration-300"
              />
              <span class="text-center font-medium text-sm leading-none">
                {{ tab.label }}
              </span>
            </button>
          </div>
        </div>

        <!-- Tab Content -->
        <Transition name="fade" mode="out-in">
          <component :is="selectedTab.component" :key="selectedTabKey" />
        </Transition>
      </div>
    </div>
  </Loader>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from "vue";
import { useI18n } from "vue-i18n";
import BuyTab from "./tabs/BuyTab.vue";
import StakeTab from "./tabs/StakeTab.vue";
import HistoryTab from "./tabs/HistoryTab.vue";
import { Loader } from "./ui";
import { BuyIcon, StakeIcon, DashboardIcon } from "./icons";
import { usePresale } from "@/composables/usePresale";

const { t } = useI18n();
const presale = usePresale();

const tabs = computed(() => [
  {
    label: t("presale.tabs.buy"),
    key: "buy",
    icon: BuyIcon,
    component: BuyTab,
  },
  {
    label: t("presale.tabs.stake"),
    key: "stake",
    icon: StakeIcon,
    component: StakeTab,
  },
  {
    label: t("presale.tabs.dashboard"),
    key: "history",
    icon: DashboardIcon,
    component: HistoryTab,
  },
]);

const selectedTabKey = ref("buy");
const selectedTab = computed(() =>
  tabs.value.find((tab) => tab.key === selectedTabKey.value)
);
const innerRef = ref(null);

const isLoading = computed(() => {
  return (
    presale.apiData.stageLoading.value ||
    presale.apiData.paymentTokensLoading.value
  );
});

const setSelectedTabKey = (key) => {
  selectedTabKey.value = key;
};

// Resize observer for smooth height transitions
let resizeObserver = null;

onMounted(() => {
  if (!innerRef.value) return;
  resizeObserver = new ResizeObserver(() => {
    // Height is handled via CSS flex
  });
  resizeObserver.observe(innerRef.value);
});

onUnmounted(() => {
  if (resizeObserver) {
    resizeObserver.disconnect();
  }
});
</script>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.15s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>

// presale-widget/components/Widget/Widget.tsx
"use client";

import clsx from "clsx";
import BuyTab from "./tabs/BuyTab";
import HistoryTab from "./tabs/HistoryTab";
import StakeTab from "./tabs/StakeTab";

import {
  CircleDollarSign as BuyIcon,
  LockKeyhole as StakeIcon,
  HistoryIcon,
} from "lucide-react";
import { CSSProperties, useEffect, useMemo, useState } from "react";
import { useAccount } from "wagmi";
import { Loader } from "./components/Loader";
import { useApiState } from "../../presale-gg/stores";
import { useTranslations } from "next-intl";

const Widget = () => {
  const t = useTranslations("widget.tabs");

  const tabs = [
    {
      label: t("buy"),
      key: "buy",
      icon: BuyIcon,
      component: BuyTab,
      needsConnected: false,
    },
    {
      label: t("stake"),
      key: "stake",
      icon: StakeIcon,
      component: StakeTab,
      needsConnected: true,
    },
    {
      label: t("dashboard"),
      key: "history",
      icon: HistoryIcon,
      component: HistoryTab,
      needsConnected: true,
    },
  ];
  const [selectedTabKey, setSelectedTabKey] = useState("buy");
  const selectedTab = useMemo(
    () => tabs.find((tab) => tab.key === selectedTabKey)!,
    [selectedTabKey]
  );
  const Component = selectedTab.component;

  const [widgetHeight, setWidgetHeight] = useState("auto");
  const [innerRef, setInnerRef] = useState<HTMLElement | null>(null);
  const MIN_HEIGHT = 200;

  useEffect(() => {
    if (!innerRef) return;
    const func = () => {
      const { height } = innerRef.getBoundingClientRect();
      setWidgetHeight(`${Math.max(height, MIN_HEIGHT)}px`);
    };
    const resizeObserver = new ResizeObserver(func);
    resizeObserver.observe(innerRef);
    window.addEventListener("resize", func);
    func();
    return () => {
      resizeObserver.disconnect();
      window.removeEventListener("resize", func);
    };
  }, [innerRef]);

  const accountData = useAccount();
  const apiData = useApiState();

  useEffect(() => {
    if (selectedTab.needsConnected && !accountData.isConnected)
      setSelectedTabKey("buy");
  }, [accountData.isConnected, selectedTab]);

  return (
    <Loader loading={apiData.stageLoading || apiData.paymentTokensLoading}>
      <div
        className="flex flex-col w-full max-w-md bg-[#002286] rounded-xl border border-[#fff] text-[#fff] overflow-y-clip font-normal"
        style={
          {
            height: "50.5rem",
            maxHeight: "50.5rem",
            transition: "height 200ms ease-out",
            "--text-secondary": "#aaa",
            "--border": "#fff",
          } as CSSProperties
        }
      >
        <div
          className="flex flex-col gap-3 flex-shrink-0 p-4 max-sm:p-3 justify-between flex-1 h-0"
          ref={setInnerRef}
        >
          <div className="flex gap-2 flex-shrink-0 border border-[#fff] rounded-full p-1">
            {tabs.map((tab) => {
              const Icon = tab.icon;
              const disabled = tab.needsConnected && !accountData.isConnected;
              return (
                <button
                  disabled={disabled}
                  title={disabled ? t("connectWallet") : undefined}
                  className={clsx(
                    "flex gap-1 items-center justify-center rounded-full flex-1 hover:bg-[rgba(0,0,0,0.1)] transition-colors font-normal px-2 max-sm:text-sm h-8 max-sm:h-[1.75rem]",
                    {
                      "!bg-[#007BF9] text-[#fff]": selectedTab.key === tab.key,
                      "!bg-[rgba(255,255,255,0.4)] text-[#444] cursor-not-allowed":
                        disabled,
                    }
                  )}
                  key={tab.key}
                  onClick={() => setSelectedTabKey(tab.key)}
                >
                  <Icon className="w-[1.25em] h-[1.25em]" />
                  {tab.label}
                </button>
              );
            })}
          </div>
          <Component />
        </div>
      </div>
    </Loader>
  );
};

export default Widget;
