// src/components/PresaleWidget/stage/StageBox.vue
<template>
  <div class="flex flex-col gap-3">
    <!-- Stage Name -->
    <p
      class="text-center text-white font-grotesk text-lg font-semibold leading-none"
    >
      {{ stageName }}
    </p>

    <!-- Current Price Card -->
    <div
      class="flex flex-col items-center self-stretch p-4 gap-2 rounded-2xl border border-white/20 bg-[rgba(8,12,35,0.48)]"
    >
      <!-- Amount Raised -->
      <template v-if="isLoading">
        <Skeleton class="h-7 w-24" />
      </template>
      <p
        v-else
        class="text-center text-white font-crisis text-2xl leading-none"
        style="
          font-weight: 400;
          -webkit-font-smoothing: antialiased;
          -moz-osx-font-smoothing: grayscale;
        "
      >
        {{ formattedRaised }}
      </p>

      <!-- Labels -->
      <div class="flex items-center justify-between w-full">
        <span class="text-white font-grotesk text-xs font-normal leading-none">
          {{ progressPercent }}% {{ t("presale.stageBox.untilPriceRise") }}
        </span>
        <span class="text-white font-grotesk text-xs font-normal leading-none">
          {{ t("presale.stageBox.of") }} {{ formattedTarget }}
        </span>
      </div>

      <!-- Progress Bar -->
      <ProgressBar :progress="stageFrac * 100" variant="striped" size="md" />

      <!-- Participants -->
      <p
        class="text-white text-center w-full font-grotesk text-xs font-normal leading-none"
      >
        {{ formattedParticipants }} {{ t("presale.stageBox.participants") }}
      </p>
    </div>
  </div>
</template>

<script setup>
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import { ProgressBar, Skeleton } from "../ui";
import { usePresale } from "@/composables/usePresale";
import { formatDollar, formatNumber, parseNum } from "@/utils/format";
import { DEFAULT_STAGE_NAME } from "@/config/presale";

const { t } = useI18n();
const presale = usePresale();

const isLoading = computed(() => presale.apiData.stageLoading.value);

const stageName = computed(() => {
  return presale.stage.value?.stage_name || DEFAULT_STAGE_NAME;
});

const stageFrac = computed(() => {
  const raised = parseNum(presale.stage.value?.cumulative_usd_raised);
  const target = parseNum(presale.stage.value?.next_stage_target_usd) || 1;
  return Math.min(raised / target, 1);
});

const progressPercent = computed(() => {
  return Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(
    stageFrac.value * 100
  );
});

const formattedRaised = computed(() => {
  return formatDollar(
    parseNum(presale.stage.value?.cumulative_usd_raised),
    true,
    0,
    0
  );
});

const formattedTarget = computed(() => {
  return formatDollar(
    parseNum(presale.stage.value?.next_stage_target_usd),
    true,
    0,
    0
  );
});

const formattedParticipants = computed(() => {
  return formatNumber(parseNum(presale.apiData.info.value?.holders ?? 0));
});
</script>

// presale-widget/components/Widget/components/StageBox.tsx
import { useApiState } from "../../../presale-gg/stores";
import { formatDollar, formatNumber, parseNum } from "../../../presale-gg/util";
import { useMemo } from "react";
import { Loadable } from "./Loader";
import { useTranslations } from "next-intl";

const StageBox = () => {
  const t = useTranslations("widget.stage");
  const apiData = useApiState();
  const stageFrac = useMemo(() => {
    return (
      parseNum(apiData.stage?.cumulative_usd_raised) /
      parseNum(apiData.stage?.next_stage_target_usd ?? 1)
    );
  }, [apiData.stage?.cumulative_usd_raised]);

  return (
    <div className="p-2 bg-[#4473C5] rounded-2xl flex flex-col gap-1 border border-[#007BF9]">
      <Loadable
        component="p"
        className="flex flex-col text-center text-2xl self-center font-bold"
      >
        {formatDollar(parseNum(apiData.stage?.cumulative_usd_raised))}
      </Loadable>
      <div className="flex flex-col">
        <Loadable component="p" className="text-xs">
          {Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(
            parseNum(stageFrac * 100)
          )}
          % {t("untilPriceRise")}
        </Loadable>
        <div className="flex bg-[rgba(0,0,0,0.2)] rounded-full h-3">
          <div
            className="h-full bg-[#007BF9] rounded-full"
            style={{ flex: stageFrac }}
          />
        </div>
        <Loadable component="p" className="text-xs text-right self-end">
          {t("of")}{" "}
          {formatDollar(
            parseNum(apiData.stage?.next_stage_target_usd),
            true,
            0,
            0
          )}
        </Loadable>
      </div>
      <Loadable component="p" className="text-center self-center">
        {formatNumber(parseNum(apiData.info?.holders))} {t("participants")}
      </Loadable>
    </div>
  );
};

export default StageBox;
